apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: LSlOMlNDaXRKJGhyUDldUUhYQ3M=
  POSTGRES_DB: bjhu
  POSTGRES_NON_ROOT_USER: bjhu
  POSTGRES_NON_ROOT_PASSWORD: LSlOMlNDaXRKJGhyUDldUUhYQ3M=
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  N8N_ENCRYPTION_KEY: LSlOMlNDaXRKJGhyUDldUUhYQ3NjQnReUDtPNnRLdFI=
