apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n
type: Opaque
data:
  # Use base64 encoded values: echo -n "your-value" | base64
  POSTGRES_USER: <base64-encoded-value>           # Example: cG9zdGdyZXM=
  POSTGRES_PASSWORD: <base64-encoded-value>       # Strong password
  POSTGRES_NON_ROOT_USER: <base64-encoded-value>  # Example: bjhu
  POSTGRES_NON_ROOT_PASSWORD: <base64-encoded-value> # Strong password
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  # Use base64 encoded values: echo -n "your-value" | base64
  N8N_ENCRYPTION_KEY: <base64-encoded-value>      # Strong random key
